version: "3.9"

services:
  database:
    image: postgres:15
    container_name: swaphub-database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: 
      - .env
    networks:
      - swaphub-network

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - ./backend:/swaphub
      - static_volume:/swaphub/static
      - media_volume:/swaphub/media
    env_file: 
      - .env
    networks:
      - swaphub-network
    environment:
      - DJANGO_SETTINGS_MODULE=swaphub.settings
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - swaphub-network
  
  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    networks:
      - swaphub-network
    depends_on:
      - backend
      - frontend

volumes:
  static_volume:
  media_volume:
  pgdata:

networks:
  swaphub-network:
    driver: bridge
